### ISSUE TITLE
Add support for sending NCCO with an outbound call

### ISSUE THREAD

**Issue by weekaung** [Vonage/vonage-go-sdk#20]
I wonder if this functionality has been implemented or not. Or do someone have a code snippet on how to send a "text-to-speech" using NCCO. Very much appreciate your help.

**Comment by lornajane** [comment]
Thanks for mentioning this, you're correct that we don't have support for the new NCCO feature yet in this library (but hey, now it's on our todo list!). For now, the best thing to do is to make a call (example here https://github.com/nexmo-community/nexmo-go#make-a-phone-call ) and serve the NCCO from your `answer_url`.

Hope that helps, please let us know if you have more questions?

**Comment by lornajane** [comment]
The library now has support for making a call with NCCO - take a look at https://vonage.github.io/vonage-go-sdk/examples/voice#make-a-phone-call for an example of how to do this. Also beware that we did some major changes to the library so you won't be able to upgrade to the newer version without updating your code as well, sorry. Do let us know how you get on!
