### ISSUE TITLE
Add Custom JSON Marshalling to NCCO

### ISSUE THREAD

**Issue by lornajane** [Vonage/vonage-go-sdk#39]
When we make an API call, we can just pass in the NCCO as an object and the library handles everything for us. When returning an NCCO response, the user needs to call `GetActions()` themselves. As a helper feature, make the NCCO do this by itself when it is JSON-Marshalled.

**Comment by avinashdhinwa** [comment]
@lornajane Can I work on this?

**Comment by lornajane** [comment]
Please go ahead, thanks :)

**Comment by lornajane** [comment]
Merged and released in v0.12.1

**Comment by ruskibenya** [comment]
@avinashdhinwa, do you mind if we shout you out for this awesome contribution on twitter? [This is you?](https://twitter.com/avinashdhinwa)

**Comment by avinashdhinwa** [comment]
> @avinashdhinwa, do you mind if we shout you out for this awesome contribution on twitter? [This is you?](https://twitter.com/avinashdhinwa)

@ruskibenya Yes, this is me. I would be more than happy for this.
