### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by Wizhi** [Vonage/vonage-go-sdk#59]
Hello,

I'm trying to simply import this module to my project, but go doesn't seem to like it:

```
❯ go get 'github.com/Vonage/vonage-go-sdk'
go: github.com/Vonage/vonage-go-sdk@v0.13.1: parsing go.mod:
	module declares its path as: github.com/vonage/vonage-go-sdk
	        but was required as: github.com/Vonage/vonage-go-sdk
```

To be clear, simply importing the library in code and having the toolchain automatically pick it up is also not working.

After some searching around, I've found a couple of articles related to the issue, but haven't been able to solve it.

- https://markcz.wordpress.com/2020/04/14/solving-module-declares-its-path-as-x-but-was-required-as-y/
- https://stackoverflow.com/questions/61311436/how-to-fix-parsing-go-mod-module-declares-its-path-as-x-but-was-required-as-y

I'm still relatively new to go, and the module system is a bit confusing at times, so maybe i'm doing something wrong here.

Any help would be appreciated.

```
❯ go version
go version go1.16 linux/amd64
```

**Comment by GregHolmes** [comment]
Hi @Wizhi ,

I believe it may be a casing issue. You're trying to get the package from the organisation Vonage with a capital V. While the `go.mod` file defines it with `module github.com/vonage/vonage-go-sdk`

Could you try the following instead:

```bash
go get 'github.com/vonage/vonage-go-sdk'
```

**Comment by Wizhi** [comment]
That was indeed _the case_ - I'll show myself out.

Dumb mistake on my part, I simply copy pasted the url.

Thanks a bunch. :)
